server:
  port: 8099
  servlet:
    context-path: /shopping-b

#数据库链接
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 666666
#    url: jdbc:mysql://localhost:3303/general_test?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://123.57.80.168:3306/shopping_mall?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true



mybatis:
  mapper-locations: classpath:/mappers/*.xml
#  config-location: classpath:/application.yml


logging:
  file: /log/shopping-b.log
##  file:
##    path: D:\java\Study_SpringBoot_Demo\log\
#  pattern:
#    console: "%d - %msg%n"
#  level: debug